### ISSUE TITLE
Implement RSS feeds

### ISSUE THREAD

**Issue by flaki** [flaki/musings#6]
[for popular request :)](https://twitter.com/denschub/status/1046518225427673093)

**Comment by flaki** [comment]
https://www.npmjs.com/package/rss

**Comment by flaki** [comment]
Oh I forgot to check this off, this is now implemented at [musings.flak.is/feed.xml](https://musings.flak.is/feed.xml) @denschub you are welcome! 🤗

**Comment by skyschub** [comment]
Took three years to implement, 0/10, horrible customer service.

Oh wait this is Flakis blog! Awesome. Thanks for pinging as well, I would have forget otherwise :D

**Comment by flaki** [comment]
In my defense this landed on May 1st, so only 2.5 years :P
So blame the marketing/community person* for not making more noise about this until now, not me!!

(*it's also me)
